# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.ico"
    keywords: Hongson Society
    backgroundpic : "img/1810-Chinese_style.jpg"

Intro:
    name: Hongson Society
    slogan: 匯聲社是港大PGSA旗下的藝術愛好者社團，也是香港大學主要面對研究生群體的最大的涵蓋藝術、文化、體育等多方面的綜合類興趣社團。其下分為音樂中心、舞蹈中心、話劇中心、體育中心等
    HeadButton: Hongson Society

Nav:
    Home_name: Index
    is_use_categories : true 
    categories_name: Categories
    is_use_archives : false
    archives_name: Archives
    
    #Social
    # for more icons, please see http://fontawesome.io/icons/#brand
    icon:
        instagram: https://www.instagram.com/hkuhas/
        facebook: https://www.facebook.com/hkuhas
        youtube: https://www.youtube.com/channel/UCfdLTs4dGXcT00rboRK279g
        
    pages:
        About: 
            link: "/about/"
        Member :
            link: "/member/"
        Gallery :
            link: "/gallery/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: Join us today!
    description: Hongson Society is the only interest-oriented arts society in HKU for postgraduate students! 
    pic_url: 
    goto_ulr: https://docs.google.com/forms/d/e/1FAIpQLSc9mqOrecneZX9lZI3FlC7_mzpn1WJFaebkio_QkGtRqPJBeA/viewform

Gallery :
    title: Mr.metro 
    description: The moment 

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: false
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    # 使用 valine 请先执行 npm install valine --save
    valine: # Valine Comment System https://github.com/xCss/Valine
       on: true
       appId: 'your appId'
       appKey: 'your appkey'
       notify: true
       verify: false
       placeholder: Please leave your footprints
       avatar: ''
       avatar_cdn: https://gravatar.loli.net/avatar/ # avatar CDN address, default gravatar.loli.net
       pageSize: 10 # comments of one page

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"


# Mathjax 支持库 
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML